"""Faster R-CNN data, model, training, and COCO evaluation helpers.

The module consumes the COCO JSON files generated by ``preprocess_visdrone.py``.
VisDrone categories remain 1..10 because Torchvision reserves label 0 for the
background class.
"""

from __future__ import annotations

import contextlib
import json
import time
from collections import defaultdict
from pathlib import Path
from typing import Any, Callable, Optional, Sequence

import numpy as np
from PIL import Image


VISDRONE_CLASS_NAMES = (
    "__background__",
    "pedestrian",
    "people",
    "bicycle",
    "car",
    "van",
    "truck",
    "tricycle",
    "awning-tricycle",
    "bus",
    "motor",
)


class VisDroneCocoDataset:
    """Minimal Torchvision detection dataset backed by generated COCO JSON."""

    def __init__(
        self,
        annotation_file: Path | str,
        image_root: Path | str,
        *,
        augmentation: Optional[Callable] = None,
    ) -> None:
        import torch

        self.torch = torch
        self.annotation_file = Path(annotation_file)
        self.image_root = Path(image_root)
        self.augmentation = augmentation
        payload = json.loads(self.annotation_file.read_text(encoding="utf-8"))
        self.images = sorted(payload["images"], key=lambda item: int(item["id"]))
        self.annotations_by_image: dict[int, list[dict[str, Any]]] = defaultdict(list)
        for annotation in payload["annotations"]:
            self.annotations_by_image[int(annotation["image_id"])].append(annotation)
        self.categories = {
            int(category["id"]): str(category["name"])
            for category in payload["categories"]
        }

    def __len__(self) -> int:
        return len(self.images)

    def get_height_and_width(self, index: int) -> tuple[int, int]:
        info = self.images[index]
        return int(info["height"]), int(info["width"])

    def __getitem__(self, index: int):
        import torch
        from torchvision.transforms.functional import pil_to_tensor

        image_info = self.images[index]
        image_id = int(image_info["id"])
        image_path = self.image_root / image_info["file_name"]
        if not image_path.is_file():
            raise FileNotFoundError(f"Missing image referenced by COCO JSON: {image_path}")
        image = Image.open(image_path).convert("RGB")

        boxes: list[list[float]] = []
        labels: list[int] = []
        iscrowd: list[int] = []
        for annotation in self.annotations_by_image.get(image_id, []):
            x, y, width, height = map(float, annotation["bbox"])
            if width <= 0 or height <= 0:
                continue
            boxes.append([x, y, x + width, y + height])
            labels.append(int(annotation["category_id"]))
            iscrowd.append(int(annotation.get("iscrowd", 0)))

        box_array = np.asarray(boxes, dtype=np.float32).reshape(-1, 4)
        label_array = np.asarray(labels, dtype=np.int64)
        crowd_array = np.asarray(iscrowd, dtype=np.int64)
        if self.augmentation is not None:
            image, box_array, label_array, _ = self.augmentation(
                image, box_array, label_array
            )
            # Augmentation may filter boxes; retained VisDrone instances are not crowd.
            crowd_array = np.zeros(len(label_array), dtype=np.int64)

        image_tensor = pil_to_tensor(image).to(dtype=torch.float32).div(255.0)
        box_tensor = torch.as_tensor(box_array, dtype=torch.float32).reshape(-1, 4)
        label_tensor = torch.as_tensor(label_array, dtype=torch.int64)
        area = (
            (box_tensor[:, 2] - box_tensor[:, 0])
            * (box_tensor[:, 3] - box_tensor[:, 1])
        )
        target = {
            "boxes": box_tensor,
            "labels": label_tensor,
            "image_id": torch.tensor(image_id, dtype=torch.int64),
            "area": area,
            "iscrowd": torch.as_tensor(crowd_array, dtype=torch.int64),
            "original_size": torch.tensor([image.height, image.width], dtype=torch.int64),
        }
        return image_tensor, target


def detection_collate_fn(batch):
    """Keep variable-size images and targets as tuples."""

    return tuple(zip(*batch))


def seed_detection_worker(worker_id: int) -> None:
    """Give each DataLoader worker an independent reproducible augmentation RNG."""

    import torch

    worker = torch.utils.data.get_worker_info()
    if worker is None:
        return
    dataset = worker.dataset
    # Handle both a direct dataset and torch.utils.data.Subset.
    while hasattr(dataset, "dataset"):
        dataset = dataset.dataset
    augmentation = getattr(dataset, "augmentation", None)
    if augmentation is not None and hasattr(augmentation, "rng"):
        augmentation.rng = np.random.default_rng(worker.seed % (2**32))


def build_faster_rcnn(
    *,
    num_classes: int = 11,
    pretrained: bool = True,
    small_anchors: bool = False,
    min_size: int = 800,
    max_size: int = 1333,
    crowded_proposals: bool = False,
    box_detections_per_img: int = 100,
    model_version: str = "v1",
):
    """Build Faster R-CNN ResNet-50-FPN for VisDrone.

    ``small_anchors=False`` is the F0/F1 baseline. Enable it only in the F2
    anchor ablation. Crowded proposal limits belong to F3/F4; F4 additionally
    selects Torchvision's improved ``v2`` detector recipe.
    """

    from torchvision.models.detection import (
        FasterRCNN_ResNet50_FPN_Weights,
        FasterRCNN_ResNet50_FPN_V2_Weights,
        fasterrcnn_resnet50_fpn,
        fasterrcnn_resnet50_fpn_v2,
    )
    from torchvision.models.detection.anchor_utils import AnchorGenerator
    from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

    model_kwargs: dict[str, Any] = {
        "min_size": min_size,
        "max_size": max_size,
        "box_detections_per_img": box_detections_per_img,
    }
    if small_anchors:
        sizes = ((8,), (16,), (32,), (64,), (128,))
        ratios = ((0.5, 1.0, 2.0),) * len(sizes)
        model_kwargs["rpn_anchor_generator"] = AnchorGenerator(sizes, ratios)
    if crowded_proposals:
        model_kwargs.update(
            rpn_pre_nms_top_n_train=4000,
            rpn_post_nms_top_n_train=2000,
            rpn_pre_nms_top_n_test=2000,
            rpn_post_nms_top_n_test=1000,
        )

    if model_version not in {"v1", "v2"}:
        raise ValueError(f"model_version must be 'v1' or 'v2', got {model_version!r}")
    if model_version == "v2":
        model_builder = fasterrcnn_resnet50_fpn_v2
        weights_enum = FasterRCNN_ResNet50_FPN_V2_Weights
    else:
        model_builder = fasterrcnn_resnet50_fpn
        weights_enum = FasterRCNN_ResNet50_FPN_Weights

    weights = weights_enum.DEFAULT if pretrained else None
    if not pretrained:
        model_kwargs["weights_backbone"] = None
    model = model_builder(weights=weights, **model_kwargs)
    input_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(input_features, num_classes)
    return model


def move_targets_to_device(targets, device):
    return [
        {key: value.to(device) if hasattr(value, "to") else value for key, value in target.items()}
        for target in targets
    ]


def train_one_epoch(
    model,
    data_loader,
    optimizer,
    device,
    *,
    scaler=None,
    max_batches: Optional[int] = None,
    accumulation_steps: int = 1,
) -> dict[str, float]:
    """Train one epoch and return mean component/total losses.

    Gradient accumulation lets memory-constrained runs retain a larger
    effective batch size. Reported losses remain unscaled.
    """

    import torch
    from tqdm.auto import tqdm

    model.train()
    if accumulation_steps < 1:
        raise ValueError("accumulation_steps must be positive")
    totals: dict[str, float] = defaultdict(float)
    batches = 0
    start = time.perf_counter()
    amp_enabled = scaler is not None and device.type == "cuda"
    total_batches = len(data_loader)
    if max_batches is not None:
        total_batches = min(total_batches, max_batches)
    progress = tqdm(data_loader, total=total_batches, desc="train", leave=False)
    optimizer.zero_grad(set_to_none=True)
    for batch_index, (images, targets) in enumerate(progress):
        if batch_index >= total_batches:
            break
        images = [image.to(device, non_blocking=True) for image in images]
        targets = move_targets_to_device(targets, device)
        amp_context = (
            torch.autocast(device_type="cuda", dtype=torch.float16)
            if amp_enabled
            else contextlib.nullcontext()
        )
        with amp_context:
            loss_dict = model(images, targets)
            loss = sum(loss_dict.values())
        if not torch.isfinite(loss):
            raise RuntimeError(f"Non-finite loss encountered: {float(loss.detach())}")
        backward_loss = loss / accumulation_steps
        if amp_enabled:
            scaler.scale(backward_loss).backward()
        else:
            backward_loss.backward()
        should_step = (
            (batch_index + 1) % accumulation_steps == 0
            or batch_index + 1 == total_batches
        )
        if should_step:
            if amp_enabled:
                scaler.step(optimizer)
                scaler.update()
            else:
                optimizer.step()
            optimizer.zero_grad(set_to_none=True)
        for name, value in loss_dict.items():
            totals[name] += float(value.detach())
        totals["loss_total"] += float(loss.detach())
        batches += 1
        progress.set_postfix(loss=f"{float(loss.detach()):.4f}")
    if batches == 0:
        raise ValueError("The training loader yielded no batches")
    result = {name: value / batches for name, value in totals.items()}
    result["seconds"] = time.perf_counter() - start
    return result


def predictions_to_coco(outputs, targets, *, score_threshold: float = 0.001):
    """Convert one detection batch to pycocotools result dictionaries."""

    results: list[dict[str, Any]] = []
    for output, target in zip(outputs, targets):
        image_id = int(target["image_id"].item())
        boxes = output["boxes"].detach().cpu()
        labels = output["labels"].detach().cpu()
        scores = output["scores"].detach().cpu()
        for box, label, score in zip(boxes, labels, scores):
            confidence = float(score)
            if confidence < score_threshold:
                continue
            x1, y1, x2, y2 = map(float, box)
            results.append(
                {
                    "image_id": image_id,
                    "category_id": int(label),
                    "bbox": [x1, y1, x2 - x1, y2 - y1],
                    "score": confidence,
                }
            )
    return results


@contextlib.contextmanager
def _silence_stdout():
    import io
    import sys

    previous = sys.stdout
    try:
        sys.stdout = io.StringIO()
        yield
    finally:
        sys.stdout = previous


def evaluate_coco(
    model,
    data_loader,
    annotation_file: Path | str,
    device,
    *,
    max_batches: Optional[int] = None,
) -> dict[str, float]:
    """Evaluate bbox AP with pycocotools and return named COCO metrics."""

    import torch
    from tqdm.auto import tqdm

    try:
        from pycocotools.coco import COCO
        from pycocotools.cocoeval import COCOeval
    except ImportError as error:
        raise ImportError("Install pycocotools to run COCO evaluation") from error

    model.eval()
    results: list[dict[str, Any]] = []
    evaluated_ids: list[int] = []
    with torch.inference_mode():
        total_batches = len(data_loader)
        if max_batches is not None:
            total_batches = min(total_batches, max_batches)
        progress = tqdm(data_loader, total=total_batches, desc="validation", leave=False)
        for batch_index, (images, targets) in enumerate(progress):
            if batch_index >= total_batches:
                break
            images = [image.to(device, non_blocking=True) for image in images]
            outputs = model(images)
            results.extend(predictions_to_coco(outputs, targets))
            evaluated_ids.extend(int(target["image_id"].item()) for target in targets)
    if not results:
        return {"map": 0.0, "map_50": 0.0, "map_75": 0.0, "map_small": 0.0}

    with _silence_stdout():
        ground_truth = COCO(str(annotation_file))
        detections = ground_truth.loadRes(results)
        evaluator = COCOeval(ground_truth, detections, "bbox")
        evaluator.params.imgIds = sorted(set(evaluated_ids))
        evaluator.evaluate()
        evaluator.accumulate()
        evaluator.summarize()
    names = (
        "map", "map_50", "map_75", "map_small", "map_medium", "map_large",
        "mar_1", "mar_10", "mar_100", "mar_small", "mar_medium", "mar_large",
    )
    return {name: float(value) for name, value in zip(names, evaluator.stats)}


def save_checkpoint(
    path: Path | str,
    *,
    model,
    optimizer,
    epoch: int,
    metrics: dict[str, float],
    config: dict[str, Any],
    scheduler=None,
    scaler=None,
    history: Optional[list[dict[str, Any]]] = None,
    best_map: Optional[float] = None,
) -> Path:
    import torch

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "epoch": epoch,
        "metrics": metrics,
        "config": config,
        "history": history or [],
        "best_map": float(best_map if best_map is not None else metrics.get("map", -1.0)),
    }
    if scheduler is not None:
        payload["scheduler"] = scheduler.state_dict()
    if scaler is not None:
        payload["scaler"] = scaler.state_dict()
    torch.save(payload, target)
    return target


def load_checkpoint(
    path: Path | str,
    *,
    model,
    optimizer=None,
    scheduler=None,
    scaler=None,
    map_location="cpu",
) -> dict[str, Any]:
    """Restore a training checkpoint and return its metadata.

    Older checkpoints without scheduler, scaler, or history remain loadable.
    """

    import torch

    checkpoint = torch.load(Path(path), map_location=map_location, weights_only=False)
    model.load_state_dict(checkpoint["model"])
    if optimizer is not None and "optimizer" in checkpoint:
        optimizer.load_state_dict(checkpoint["optimizer"])
    if scheduler is not None and "scheduler" in checkpoint:
        scheduler.load_state_dict(checkpoint["scheduler"])
    if scaler is not None and "scaler" in checkpoint:
        scaler.load_state_dict(checkpoint["scaler"])
    return {
        "epoch": int(checkpoint.get("epoch", 0)),
        "metrics": checkpoint.get("metrics", {}),
        "config": checkpoint.get("config", {}),
        "history": checkpoint.get("history", []),
        "best_map": float(
            checkpoint.get("best_map", checkpoint.get("metrics", {}).get("map", -1.0))
        ),
    }
